codecov:
  branch: *
coverage:
  ignore:
    - "src/test/**/*"
  status:
    project:
      default:
        target: 1%
        threshold: null
        if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
